######################################################################
# Automatically generated by qmake (3.0) Mi. Nov. 9 21:08:14 2016
######################################################################

QT += charts network
TEMPLATE = app
TARGET = SensorCharts
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
